/**
 * GetStaticOverlays RPC — returns static map overlay data and layer metadata for clients (e.g. iOS).
 * Data is built at deploy time by scripts/generate-static-overlays.mts so the edge bundle never
 * imports from @/ — avoiding "Cannot find package '@/utils'" on Vercel.
 */

import type {
  ServerContext,
  GetStaticOverlaysRequest,
  GetStaticOverlaysResponse,
} from '../../../../src/generated/server/worldmonitor/map/v1/service_server';

// Generated by: npm run generate-overlays (run before build)
import staticOverlaysData from './static-overlays.generated.json';

const payload = staticOverlaysData as {
  staticOverlaysJson: string;
  layerCatalog: Array<{ key: string; fallbackLabel: string; icon: string; premium: string }>;
  variantLayerOrder: Array<{ variant: string; layerKeys: string[]; svgOnlyKeys: string[] }>;
};

export async function getStaticOverlays(
  _ctx: ServerContext,
  _req: GetStaticOverlaysRequest,
): Promise<GetStaticOverlaysResponse> {
  return {
    staticOverlaysJson: payload.staticOverlaysJson,
    layerCatalog: payload.layerCatalog,
    variantLayerOrder: payload.variantLayerOrder,
  };
}
